# Generated by Django 5.0.7 on 2024-08-11 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_eventorganizers'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventorganizers',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
