# Generated by Django 5.1 on 2024-08-30 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_rename_transaction_id_payment_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='event_covers/'),
        ),
    ]
