# Generated by Django 5.1 on 2024-09-01 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='attended',
            field=models.BooleanField(default=False),
        ),
    ]
