# Generated by Django 5.1 on 2024-09-01 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_event_latitude_event_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='event',
            name='longitude',
        ),
    ]
