# Generated by Django 5.1 on 2024-09-02 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_event_latitude_event_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
