# Generated by Django 5.1.1 on 2024-09-20 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_event_location_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventSuccessMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_ratio', models.FloatField()),
                ('event_category', models.CharField(max_length=255)),
                ('community_category', models.CharField(max_length=255)),
                ('community_name', models.CharField(max_length=255)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('duration_hours', models.FloatField()),
                ('is_weekend', models.BooleanField()),
                ('is_free', models.BooleanField()),
                ('keywords', models.TextField()),
                ('is_synthetic', models.BooleanField(default=False)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='success_metrics', to='events.event')),
            ],
        ),
    ]
