# Generated by Django 5.1.1 on 2024-09-22 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_eventsuccessmetrics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsuccessmetrics',
            name='duration_hours',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='eventsuccessmetrics',
            name='event',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='success_metrics', to='events.event'),
        ),
    ]
