# Generated by Django 5.1.1 on 2024-09-25 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_alter_eventsuccessmetrics_duration_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcategory',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
