# Generated by Django 5.1.1 on 2024-09-26 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_eventcategory_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcategory',
            name='status',
            field=models.CharField(default='enabled', max_length=255),
        ),
    ]
