# Generated by Django 5.1.1 on 2024-10-07 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_alter_eventcategory_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='invoice_file',
            field=models.FileField(blank=True, null=True, upload_to='payment_invoices/'),
        ),
    ]
