# Generated by Django 4.2.18 on 2025-01-29 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_event_volunteer_tasks_volunteerregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_streaming',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='is_virtual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='stream_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='stream_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
