# Generated by Django 4.2.18 on 2025-01-30 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_event_is_streaming_event_is_virtual_event_stream_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='stream_key',
        ),
        migrations.RemoveField(
            model_name='event',
            name='stream_url',
        ),
        migrations.AddField(
            model_name='event',
            name='youtube_stream_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
