# Generated by Django 4.2.18 on 2025-01-30 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_remove_event_stream_key_remove_event_stream_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='is_virtual',
        ),
    ]
