# Generated by Django 4.2.18 on 2025-02-02 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_remove_event_is_virtual'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventGalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='event_gallery/')),
                ('item_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('poster', 'Poster')], max_length=10)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_items', to='events.event')),
            ],
            options={
                'ordering': ['-upload_date'],
            },
        ),
    ]
