# Generated by Django 4.2.18 on 2025-03-03 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_eventgalleryitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='max_attendees',
            field=models.PositiveIntegerField(default=50, help_text='Maximum number of attendees allowed for this event'),
        ),
    ]
