# Generated by Django 4.2.18 on 2025-03-03 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_event_max_attendees'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='event',
            name='dynamic_pricing_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='max_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='event',
            name='min_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='event',
            name='price_increment_percentage',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Percentage to increase/decrease price based on demand', max_digits=5),
        ),
    ]
