# Generated by Django 5.0.7 on 2024-08-11 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='tags',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='community',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
