# Generated by Django 5.0.7 on 2024-08-11 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_community_tags_community_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='member_limit',
            field=models.PositiveIntegerField(choices=[(50, '50'), (100, '100'), (250, '250')], default=50),
        ),
    ]
