# Generated by Django 5.1.1 on 2024-09-26 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0003_community_member_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitycategory',
            name='status',
            field=models.CharField(default='enabled', max_length=255),
        ),
    ]
