# Generated by Django 4.2.18 on 2025-02-03 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0004_communitycategory_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityGalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='community_gallery/')),
                ('item_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=10)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_items', to='communities.community')),
            ],
            options={
                'ordering': ['-upload_date'],
            },
        ),
    ]
