# Generated by Django 4.2.18 on 2025-02-05 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0006_chatmessage_chatroom_chatmessage_chat_room_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='is_typing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read')], default='sent', max_length=10),
        ),
    ]
