# Generated by Django 4.2.18 on 2025-02-05 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0007_chatmessage_is_typing_chatmessage_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='read_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
