# Generated by Django 4.2.18 on 2025-01-27 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='message',
            field=models.TextField(db_collation='utf8mb4_unicode_ci'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='response',
            field=models.TextField(db_collation='utf8mb4_unicode_ci'),
        ),
    ]
