"""
Django settings for evocom project.

Generated by 'django-admin startproject' using Django 5.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

SITE_URL = 'https://evocom.koyeb.app/'
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-8mzk()y1cstgu)n&g5^p_svo$0gd^yvc5dq^vl1%b3ccl=o!s4'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
     # Custom apps
    'users',
    'communities',
    'evocom_admin',
    'events',
    'chatbot',
    
    
    'django.contrib.sites',  
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'django_otp',
    'django_otp.plugins.otp_totp',
]

AUTH_USER_MODEL = 'users.User'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'events.middleware.ReminderMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django_otp.middleware.OTPMiddleware',
]

ROOT_URLCONF = 'evocom.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'evocom.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'evocom_postmiddle',
        'USER': 'evocom_postmiddle',
        'PASSWORD': '8384085adf5855c7cc90ba7211c50379306aefb0',
        'HOST': '68mko.h.filess.io',
        'PORT': '61000',
        'OPTIONS': {
            'charset': 'utf8mb4',
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/


STATIC_URL = 'static/'
STATICFILES_DIRS=[os.path.join(BASE_DIR, 'static')]
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
LOGIN_URL = '/login/'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'  # Use your email provider's SMTP server
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'evocomindia@gmail.com'
EMAIL_HOST_PASSWORD = 'xerm vuuc pmal mvvl'
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

SITE_ID = 2

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]


SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        },
        'OAUTH_PKCE_ENABLED': True,
    }
}


LOGIN_REDIRECT_URL = 'users:loginfn'
LOGOUT_REDIRECT_URL = 'users:logout'

# Additional settings for email verification and sign up
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'
ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_USERNAME_REQUIRED = False
SOCIALACCOUNT_LOGIN_ON_GET=True


STRIPE_PUBLISHABLE_KEY = 'pk_test_51Pt9v92NqMToBdgAst7v14ykmbvKCNP6P47RJLFfc9CIuICBHYBjJ1KKeHUVCKd8tvorfKTSAyGjz0QWHmWFxksT00tvy0xFig'
STRIPE_SECRET_KEY = 'sk_test_51Pt9v92NqMToBdgAl36iHFblsffGVdmwO7Vu9crgAV2yFYLtElkiVffPuTTxixw4u06FJhSVHtSX0CPcGXTSpswO00mVu3dYca'

RAZORPAY_KEY_ID = 'rzp_test_1vZK3GexmGW5zt'
RAZORPAY_KEY_SECRET = 'eIKYygydEQ5iicHT2N6gaVuC'

# OpenAI Configuration
OPENAI_API_KEY = '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'

# HuggingFace Configuration
HUGGINGFACE_API_KEY = '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'
HUGGINGFACE_API_URL = "https://api-inference.huggingface.co/models/mistralai/Mistral-7B-Instruct-v0.2"

# Streaming Settings
RTMP_SERVER = {
    'RTMP_URL': 'rtmp://localhost/live',  # Base RTMP URL
    'HLS_URL': 'http://localhost/hls',    # HLS URL for viewers
    'STREAM_KEY_LENGTH': 16,              # Length of generated stream keys
    'CORS_ORIGINS': [
        'http://localhost:8000',
        'https://your-domain.com'
    ]
}
